### PR TITLE
Admin Dashboard - Top Header w/ Tabs and Admin Dashboard - Table - Role Header

### PR DESCRIPTION
**Pull request by christopherabey**
## [Design Video](https://www.loom.com/share/647d8564027b43b9b81c6ae49ee89274) 
Covers:
* Logo button redirect
* Selecting different views in the dropdown
* Settings / profile buttons don't have functionality yet (we should cover this in later tickets)
* Department buttons - hover and active states
* Role buttons - hover and active states
* [A11y] Focus states when navigating by keyboard

### Notion ticket link

[Admin Dashboard - Top Header w/ Tabs](https://www.notion.so/uwblueprintexecs/Admin-Dashboard-Top-Header-w-Tabs-4b2d876710a5493a9baf99272d068787)

[Admin Dashboard - Table - Role Header](https://www.notion.so/uwblueprintexecs/Admin-Dashboard-Table-Role-Header-6a785ee555274c89817ca47ec204cd11)

### Implementation description

- Added header with tabs to the admin dashboard
- Added role header to the admin dashboard

check against https://www.figma.com/file/z0heicLtAk7PBC48xiD9hU/Application-Dashboard?node-id=195%3A1176&t=XLsBe30CVtHB2qLM-1

### Steps to test

1. Run yarn dev
2. Navigate to localhost:3000/admin

i didn't make the Users a prop just for testing but it should be pretty easy to do that.

### Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] I have run the linter
- [x] I have requested a review from other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by mslwang** [comment]
Looks great so far! Do you think you could show me what it's like to have one of the tabs selected?

**Comment by Jaishreebala** [comment]
Hello! Good job on the ticket so far! There are a couple of changes to make. 
Sidenote: the final designs are under prototypes: https://www.figma.com/file/z0heicLtAk7PBC48xiD9hU/Application-Dashboard?node-id=215%3A4883&t=32CUWpqyoWohibEy-1
The tab should look similar to this:
Screen Shot 2023-04-08 at 3 30 27 PM

Here are the exact changes to make 
- [ ] The font looks different 
- [ ] blue background for the top header 
- [ ] icons on the right don't match up (settings and icon)
- [ ] blueprint application dashboard dropdown looks different (blue background instead of blue outline)
- [ ] drop shadow under the teams tab (community, developers, design, product)
- [ ] the color of the selected team has to be changed 
- [ ] padding of the roles (developer, product manager) doesn't seem to match

**Review by aaggarwal10 — COMMENTED** [review]
All the CI is failing. Can you take a look into why that is the case?

**Review by aaggarwal10 — APPROVED** [review]
LGTM 👍

**Pull request merged**
